# Tabluar data pre-processong

# import all required libraries

In [2]:

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random
np.random.seed(42)
random.seed(42)

# load data set

In [4]:
df=pd.read_csv('input_table.csv')

In [ ]:
df.head(100)

,Invoice ID,City,Gender,Product line,Unit price,Quantity,Total,Date,Payment,gross income,Rating
0,750-67-8428,Yangon,Female,Health and beauty,74.69,7,548.9715,1/5/2019,Ewallet,26.1415,9.1
1,226-31-3081,Naypyitaw,Female,Electronic accessories,15.28,5,80.2200,3/8/2019,Cash,3.8200,9.6
2,631-41-3108,Yangon,Male,Home and lifestyle,46.33,7,340.5255,3/3/2019,Credit card,16.2155,7.4
3,123-19-1176,Yangon,Male,Health and beauty,58.22,8,489.0480,1/27/2019,Ewallet,23.2880,8.4
4,373-73-7910,Yangon,Male,Sports and travel,86.31,7,634.3785,2/8/2019,Ewallet,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...
95,594-34-4444,Yangon,Male,Electronic accessories,97.16,1,102.0180,3/8/2019,Ewallet,4.8580,7.2
96,766-85-7061,Mandalay,Male,Health and beauty,87.87,10,922.6350,3/29/2019,Ewallet,43.9350,5.1
97,871-39-9221,Naypyitaw,Female,Electronic accessories,12.45,6,78.4350,2/9/2019,Cash,3.7350,4.1
98,865-92-6136,Yangon,Male,Food and beverages,52.75,3,166.1625,3/23/2019,Ewallet,7.9125,9.3
99,733-01-9107,Mandalay,Male,Home and lifestyle,82.70,6,521.0100,3/5/2019,Cash,24.8100,7.4

In [5]:


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Invoice ID    1000 non-null   object
 1   City          1000 non-null   object
 2   Gender        1000 non-null   object
 3   Product line  1000 non-null   object
 4   Unit price    1000 non-null   float64
 5   Quantity      1000 non-null   int64
 6   Total         1000 non-null   float64
 7   Date          1000 non-null   object
 8   Payment       1000 non-null   object
 9   gross income  1000 non-null   float64
 10  Rating        1000 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 86.1+ KB

In [6]:


df.isna().sum()

Invoice ID      0
City            0
Gender          0
Product line    0
Unit price      0
Quantity        0
Total           0
Date            0
Payment         0
gross income    0
Rating          0
dtype: int64

In [7]:
df.isna().sum()

Invoice ID      0
City            0
Gender          0
Product line    0
Unit price      0
Quantity        0
Total           0
Date            0
Payment         0
gross income    0
Rating          0
dtype: int64

In [8]:
df['Date'].unique()

array(['1/5/2019', '3/8/2019', '3/3/2019', '1/27/2019', '2/8/2019',
       '3/25/2019', '2/25/2019', '2/24/2019', '1/10/2019', '2/20/2019',
       '2/6/2019', '3/9/2019', '2/12/2019', '2/7/2019', '3/29/2019',
       '1/15/2019', '3/11/2019', '1/1/2019', '1/21/2019', '3/5/2019',
       '3/15/2019', '2/17/2019', '3/2/2019', '3/22/2019', '3/10/2019',
       '1/25/2019', '1/28/2019', '1/7/2019', '3/23/2019', '1/17/2019',
       '2/2/2019', '3/4/2019', '3/16/2019', '2/27/2019', '2/10/2019',
       '3/19/2019', '2/3/2019', '3/7/2019', '2/28/2019', '3/27/2019',
       '1/20/2019', '3/12/2019', '2/15/2019', '3/6/2019', '2/14/2019',
       '3/13/2019', '1/24/2019', '1/6/2019', '2/11/2019', '1/22/2019',
       '1/13/2019', '1/9/2019', '1/12/2019', '1/26/2019', '1/23/2019',
       '2/23/2019', '1/2/2019', '2/9/2019', '3/26/2019', '3/1/2019',
       '2/1/2019', '3/28/2019', '3/24/2019', '2/5/2019', '1/19/2019',
       '1/16/2019', '1/8/2019', '2/18/2019', '1/18/2019', '2/16/2019',
       '2/22/2019', '1/29/2019', '1/4/2019', '3/30/2019', '1/30/2019',
       '1/3/2019', '3/21/2019', '2/13/2019', '1/14/2019', '3/18/2019',
       '3/20/2019', '2/21/2019', '1/31/2019', '1/11/2019', '2/26/2019',
       '3/17/2019', '3/14/2019', '2/4/2019', '2/19/2019'], dtype=object)

In [9]:
df["Total"] = df["Total"].round(2)

In [10]:
print(df)

      Invoice ID       City  Gender            Product line  Unit price  \
0    750-67-8428     Yangon  Female       Health and beauty       74.69
1    226-31-3081  Naypyitaw  Female  Electronic accessories       15.28
2    631-41-3108     Yangon    Male      Home and lifestyle       46.33
3    123-19-1176     Yangon    Male       Health and beauty       58.22
4    373-73-7910     Yangon    Male       Sports and travel       86.31
..           ...        ...     ...                     ...         ...
995  233-67-5758  Naypyitaw    Male       Health and beauty       40.35
996  303-96-2227   Mandalay  Female      Home and lifestyle       97.38
997  727-02-1313     Yangon    Male      Food and beverages       31.84
998  347-56-2442     Yangon    Male      Home and lifestyle       65.82
999  849-09-3807     Yangon  Female     Fashion accessories       88.34

     Quantity    Total       Date      Payment  gross income  Rating
0           7   548.97   1/5/2019      Ewallet       26.1415     9.1
1           5    80.22   3/8/2019         Cash        3.8200     9.6
2           7   340.53   3/3/2019  Credit card       16.2155     7.4
3           8   489.05  1/27/2019      Ewallet       23.2880     8.4
4           7   634.38   2/8/2019      Ewallet       30.2085     5.3
..        ...      ...        ...          ...           ...     ...
995         1    42.37  1/29/2019      Ewallet        2.0175     6.2
996        10  1022.49   3/2/2019      Ewallet       48.6900     4.4
997         1    33.43   2/9/2019         Cash        1.5920     7.7
998         1    69.11  2/22/2019         Cash        3.2910     4.1
999         7   649.30  2/18/2019         Cash       30.9190     6.6

[1000 rows x 11 columns]

In [11]:
duplicate_count = df.duplicated(subset="Invoice ID").sum()
print(f"Number of duplicate Invoice IDs: {duplicate_count}")

Number of duplicate Invoice IDs: 0

In [12]:
df_cleaned = df.drop_duplicates(subset="Invoice ID", keep="first")

In [13]:
df["Calculated Gross Income"] = df["Total"] * 0.05

In [14]:
df["Calculated Gross Income"] = df["Calculated Gross Income"].round(2)

In [15]:
print(df)

      Invoice ID       City  Gender            Product line  Unit price  \
0    750-67-8428     Yangon  Female       Health and beauty       74.69
1    226-31-3081  Naypyitaw  Female  Electronic accessories       15.28
2    631-41-3108     Yangon    Male      Home and lifestyle       46.33
3    123-19-1176     Yangon    Male       Health and beauty       58.22
4    373-73-7910     Yangon    Male       Sports and travel       86.31
..           ...        ...     ...                     ...         ...
995  233-67-5758  Naypyitaw    Male       Health and beauty       40.35
996  303-96-2227   Mandalay  Female      Home and lifestyle       97.38
997  727-02-1313     Yangon    Male      Food and beverages       31.84
998  347-56-2442     Yangon    Male      Home and lifestyle       65.82
999  849-09-3807     Yangon  Female     Fashion accessories       88.34

     Quantity    Total       Date      Payment  gross income  Rating  \
0           7   548.97   1/5/2019      Ewallet       26.1415     9.1
1           5    80.22   3/8/2019         Cash        3.8200     9.6
2           7   340.53   3/3/2019  Credit card       16.2155     7.4
3           8   489.05  1/27/2019      Ewallet       23.2880     8.4
4           7   634.38   2/8/2019      Ewallet       30.2085     5.3
..        ...      ...        ...          ...           ...     ...
995         1    42.37  1/29/2019      Ewallet        2.0175     6.2
996        10  1022.49   3/2/2019      Ewallet       48.6900     4.4
997         1    33.43   2/9/2019         Cash        1.5920     7.7
998         1    69.11  2/22/2019         Cash        3.2910     4.1
999         7   649.30  2/18/2019         Cash       30.9190     6.6

     Calculated Gross Income
0                      27.45
1                       4.01
2                      17.03
3                      24.45
4                      31.72
..                       ...
995                     2.12
996                    51.12
997                     1.67
998                     3.46
999                    32.46

[1000 rows x 12 columns]

In [16]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df["Date"] = df["Date"].dt.strftime("%Y-%m-%d")
print(df)

      Invoice ID       City  Gender            Product line  Unit price  \
0    750-67-8428     Yangon  Female       Health and beauty       74.69
1    226-31-3081  Naypyitaw  Female  Electronic accessories       15.28
2    631-41-3108     Yangon    Male      Home and lifestyle       46.33
3    123-19-1176     Yangon    Male       Health and beauty       58.22
4    373-73-7910     Yangon    Male       Sports and travel       86.31
..           ...        ...     ...                     ...         ...
995  233-67-5758  Naypyitaw    Male       Health and beauty       40.35
996  303-96-2227   Mandalay  Female      Home and lifestyle       97.38
997  727-02-1313     Yangon    Male      Food and beverages       31.84
998  347-56-2442     Yangon    Male      Home and lifestyle       65.82
999  849-09-3807     Yangon  Female     Fashion accessories       88.34

     Quantity    Total        Date      Payment  gross income  Rating  \
0           7   548.97  2019-01-05      Ewallet       26.1415     9.1
1           5    80.22  2019-03-08         Cash        3.8200     9.6
2           7   340.53  2019-03-03  Credit card       16.2155     7.4
3           8   489.05  2019-01-27      Ewallet       23.2880     8.4
4           7   634.38  2019-02-08      Ewallet       30.2085     5.3
..        ...      ...         ...          ...           ...     ...
995         1    42.37  2019-01-29      Ewallet        2.0175     6.2
996        10  1022.49  2019-03-02      Ewallet       48.6900     4.4
997         1    33.43  2019-02-09         Cash        1.5920     7.7
998         1    69.11  2019-02-22         Cash        3.2910     4.1
999         7   649.30  2019-02-18         Cash       30.9190     6.6

     Calculated Gross Income
0                      27.45
1                       4.01
2                      17.03
3                      24.45
4                      31.72
..                       ...
995                     2.12
996                    51.12
997                     1.67
998                     3.46
999                    32.46

[1000 rows x 12 columns]

In [17]:
df["Invoice ID"] = df["Invoice ID"].astype(str).str.replace("-", "", regex=True)

In [18]:
print(df.head())

  Invoice ID       City  Gender            Product line  Unit price  Quantity  \
0  750678428     Yangon  Female       Health and beauty       74.69         7
1  226313081  Naypyitaw  Female  Electronic accessories       15.28         5
2  631413108     Yangon    Male      Home and lifestyle       46.33         7
3  123191176     Yangon    Male       Health and beauty       58.22         8
4  373737910     Yangon    Male       Sports and travel       86.31         7

    Total        Date      Payment  gross income  Rating  \
0  548.97  2019-01-05      Ewallet       26.1415     9.1
1   80.22  2019-03-08         Cash        3.8200     9.6
2  340.53  2019-03-03  Credit card       16.2155     7.4
3  489.05  2019-01-27      Ewallet       23.2880     8.4
4  634.38  2019-02-08      Ewallet       30.2085     5.3

   Calculated Gross Income
0                    27.45
1                     4.01
2                    17.03
3                    24.45
4                    31.72

In [19]:
df['Gender'] = df['Gender'].apply(lambda x: 0 if x == 'Male' else 1)

print(df)

    Invoice ID       City  Gender            Product line  Unit price  \
0    750678428     Yangon       1       Health and beauty       74.69
1    226313081  Naypyitaw       1  Electronic accessories       15.28
2    631413108     Yangon       0      Home and lifestyle       46.33
3    123191176     Yangon       0       Health and beauty       58.22
4    373737910     Yangon       0       Sports and travel       86.31
..         ...        ...     ...                     ...         ...
995  233675758  Naypyitaw       0       Health and beauty       40.35
996  303962227   Mandalay       1      Home and lifestyle       97.38
997  727021313     Yangon       0      Food and beverages       31.84
998  347562442     Yangon       0      Home and lifestyle       65.82
999  849093807     Yangon       1     Fashion accessories       88.34

     Quantity    Total        Date      Payment  gross income  Rating  \
0           7   548.97  2019-01-05      Ewallet       26.1415     9.1
1           5    80.22  2019-03-08         Cash        3.8200     9.6
2           7   340.53  2019-03-03  Credit card       16.2155     7.4
3           8   489.05  2019-01-27      Ewallet       23.2880     8.4
4           7   634.38  2019-02-08      Ewallet       30.2085     5.3
..        ...      ...         ...          ...           ...     ...
995         1    42.37  2019-01-29      Ewallet        2.0175     6.2
996        10  1022.49  2019-03-02      Ewallet       48.6900     4.4
997         1    33.43  2019-02-09         Cash        1.5920     7.7
998         1    69.11  2019-02-22         Cash        3.2910     4.1
999         7   649.30  2019-02-18         Cash       30.9190     6.6

     Calculated Gross Income
0                      27.45
1                       4.01
2                      17.03
3                      24.45
4                      31.72
..                       ...
995                     2.12
996                    51.12
997                     1.67
998                     3.46
999                    32.46

[1000 rows x 12 columns]

In [20]:
df.head()

,Invoice ID,City,Gender,Product line,Unit price,Quantity,Total,Date,Payment,gross income,Rating,Calculated Gross Income
0,750678428,Yangon,1,Health and beauty,74.69,7,548.97,2019-01-05,Ewallet,26.1415,9.1,27.45
1,226313081,Naypyitaw,1,Electronic accessories,15.28,5,80.22,2019-03-08,Cash,3.8200,9.6,4.01
2,631413108,Yangon,0,Home and lifestyle,46.33,7,340.53,2019-03-03,Credit card,16.2155,7.4,17.03
3,123191176,Yangon,0,Health and beauty,58.22,8,489.05,2019-01-27,Ewallet,23.2880,8.4,24.45
4,373737910,Yangon,0,Sports and travel,86.31,7,634.38,2019-02-08,Ewallet,30.2085,5.3,31.72

In [21]:
df['Product line'] = df['Product line'].str.strip().str.lower().str.replace(' ', '_')
df['Payment'] = df['Payment'].str.strip().str.lower().str.replace(' ', '_')

In [22]:
!pip install transformers
!pip install datasets
!pip install pandas
!pip install sentence-transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.50.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.30.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.1.31)
Collecting datasets
  Downloading datasets-3.5.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.12.0,>=2023.1.0 (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.15)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.30.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.3.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.5.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.2/491.2 kB 8.2 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 7.6 MB/s eta 0:00:00
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 11.3 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 9.3 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 11.8 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2024.12.0 which is incompatible.
Successfully installed datasets-3.5.0 dill-0.3.8 fsspec-2024.12.0 multiprocess-0.70.16 xxhash-3.5.0
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.11/dist-packages (3.4.1)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.50.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.14.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (0.30.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (11.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.12.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.13.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.1.31)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.9 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 61.4 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 51.8 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 39.7 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 797.6 kB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.9 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.1 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.6 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 2.1 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 49.0 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:

In [23]:
import pandas as pd

df = pd.read_csv("input_table.csv")
df.head()

,Invoice ID,City,Gender,Product line,Unit price,Quantity,Total,Date,Payment,gross income,Rating
0,750-67-8428,Yangon,Female,Health and beauty,74.69,7,548.9715,1/5/2019,Ewallet,26.1415,9.1
1,226-31-3081,Naypyitaw,Female,Electronic accessories,15.28,5,80.2200,3/8/2019,Cash,3.8200,9.6
2,631-41-3108,Yangon,Male,Home and lifestyle,46.33,7,340.5255,3/3/2019,Credit card,16.2155,7.4
3,123-19-1176,Yangon,Male,Health and beauty,58.22,8,489.0480,1/27/2019,Ewallet,23.2880,8.4
4,373-73-7910,Yangon,Male,Sports and travel,86.31,7,634.3785,2/8/2019,Ewallet,30.2085,5.3

In [24]:
from sentence_transformers import SentenceTransformer

# Load a pre-trained model
model = SentenceTransformer('all-MiniLM-L6-v2')  # lightweight and fast

# Create embeddings for each row (combine relevant fields)
df['combined_text'] = df.apply(lambda row: f"{row['Product line']} {row['gross income']}", axis=1)
df['embedding'] = df['combined_text'].apply(lambda x: model.encode(x))

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [25]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Example Query
query = "What is the highest gross income for health and beauty product line?"
query_embedding = model.encode(query)

# Compute similarity
df['similarity'] = df['embedding'].apply(lambda x: cosine_similarity([x], [query_embedding])[0][0])

# Get top N relevant rows
top_n = df.sort_values(by='similarity', ascending=False).head(5)
top_n[['Product line', 'gross income', 'similarity']]

          Product line  gross income  similarity
668  Health and beauty       14.3130    0.626447
776  Health and beauty       22.8585    0.588269
808  Health and beauty        0.8875    0.585420
398  Health and beauty       12.3180    0.584310
678  Health and beauty       29.4750    0.581582

In [26]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")

prompt = "What is the average gross income for electronic accessories?"  # <-- Add this!

# Tokenize
inputs = tokenizer(prompt, return_tensors="pt")
print("Input Token IDs:", inputs['input_ids'])

# Generate output token IDs
outputs = model.generate(**inputs)
print("Output Token IDs:", outputs)

# Decode output tokens to string
decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
print("Final Output:", decoded)

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Input Token IDs: tensor([[ 363,   19,    8, 1348, 8690, 2055,   21, 3031, 5513,   58,    1]])
Output Token IDs: tensor([[   0, 1514,    3, 3390,    5,  927,  770,    1]])
Final Output: $ 59.8 million

In [27]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import pandas as pd

# Load question sheet
df = pd.read_excel("myquery.xlsx")

# Load FLAN-T5 model
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-base")
model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-base")

generated_responses = []

# For each question, generate response
for q in df["question"]:
    inputs = tokenizer(q, return_tensors="pt")
    outputs = model.generate(**inputs, max_length=100)
    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
    generated_responses.append(decoded)

# Add to dataframe
df["generated response"] = generated_responses

# ✅ Overwrite original file with generated responses
df.to_excel("myquery.xlsx", index=False)

print("✅ Done! Check 'myquery.xlsx' for the results.")

✅ Done! Check 'myquery.xlsx' for the results.

In [28]:

df = pd.read_excel("myquery.xlsx")
df.head()

,question,row index,column index,answer,filtered row index,filtered column index,generated response
0,What product line is in the latest entry?,999,3,Fashion accessories,NaN,NaN,acetate
1,On what date did the first transaction occur?,"17, 245, 450, 484, 496, 523, 567, 696, 829, 83...",7,1/1/2019,NaN,NaN,1889
2,What is the latest transaction date?,"158, 306, 473, 474, 643, 646, 671, 881, 883, 9...",7,3/30/2019,NaN,NaN,"January 1, 2018"
3,what is the max rating given in home and lifes...,"2, 7, 19, 22, 25, 39, 40, 41, 54, 56, 58, 61, ...","3,10",9.9,NaN,NaN,a five star
4,How many transactions involved Male customers ...,"331, 464, 540, 708, 710","2,10",5,NaN,NaN,0

In [29]:
import pandas as pd

# Load the input table and queries
data_df = pd.read_csv("input_table.csv")
query_df = pd.read_excel("myquery.xlsx")

# Helper function to evaluate each question
def evaluate_query(q):
    q_lower = q.lower()

    try:
        if "latest entry" in q_lower and "product line" in q_lower:
            return data_df.iloc[-1]["Product line"]

        elif "first transaction" in q_lower:
            return data_df["Date"].min()

        elif "latest transaction" in q_lower:
            return data_df["Date"].max()

        elif "max rating" in q_lower and "home and lifestyle" in q_lower:
            filtered = data_df[data_df["Product line"].str.lower() == "home and lifestyle"]
            return filtered["Rating"].max()

        elif "male customers" in q_lower and "fashion accessories" in q_lower:
            filtered = data_df[(data_df["Gender"] == "Male") & (data_df["Product line"] == "Fashion accessories")]
            return len(filtered)

        elif "average gross income" in q_lower and "electronic accessories" in q_lower:
            filtered = data_df[data_df["Product line"] == "Electronic accessories"]
            return round(filtered["gross income"].mean(), 2)

        # Add more conditions as needed...

        else:
            return "Not handled"

    except Exception as e:
        return f"Error: {e}"

# Apply function to each question
query_df["evaluated answer"] = query_df["question"].apply(evaluate_query)

# Save the updated file
query_df.to_excel("myquery.xlsx", index=False)
print("✅ Done! 'evaluated answer' column added to myquery.xlsx")

✅ Done! 'evaluated answer' column added to myquery.xlsx

In [30]:
df = pd.read_excel("myquery.xlsx")
df.head()

,question,row index,column index,answer,filtered row index,filtered column index,generated response,evaluated answer
0,What product line is in the latest entry?,999,3,Fashion accessories,NaN,NaN,acetate,Fashion accessories
1,On what date did the first transaction occur?,"17, 245, 450, 484, 496, 523, 567, 696, 829, 83...",7,1/1/2019,NaN,NaN,1889,1/1/2019
2,What is the latest transaction date?,"158, 306, 473, 474, 643, 646, 671, 881, 883, 9...",7,3/30/2019,NaN,NaN,"January 1, 2018",3/9/2019
3,what is the max rating given in home and lifes...,"2, 7, 19, 22, 25, 39, 40, 41, 54, 56, 58, 61, ...","3,10",9.9,NaN,NaN,a five star,9.9
4,How many transactions involved Male customers ...,"331, 464, 540, 708, 710","2,10",5,NaN,NaN,0,Not handled

In [31]:
import pandas as pd

# Load input table and queries
input_df = pd.read_csv("input_table.csv")
query_df = pd.read_excel("myquery.xlsx")

evaluated_answers = []

# Go through each query
for idx, row in query_df.iterrows():
    try:
        # Parse row and column indexes
        row_idxs = [int(i.strip()) for i in str(row['row index']).split(',') if i.strip().isdigit()]
        col_idxs = [int(i.strip()) for i in str(row['column index']).split(',') if i.strip().isdigit()]

        # Handle case 1: single cell lookup
        if len(row_idxs) == 1 and len(col_idxs) == 1:
            evaluated = input_df.iloc[row_idxs[0], col_idxs[0]]

        # Handle case 2: multiple rows and one column (e.g., for max, min, count)
        elif len(row_idxs) > 0 and len(col_idxs) == 1:
            col_data = input_df.iloc[row_idxs, col_idxs[0]]
            # Try to infer logic from question
            q = row['question'].lower()
            if "max" in q:
                evaluated = col_data.max()
            elif "min" in q:
                evaluated = col_data.min()
            elif "average" in q or "mean" in q:
                evaluated = round(col_data.mean(), 2)
            elif "count" in q or "how many" in q:
                evaluated = len(col_data)
            else:
                evaluated = ", ".join(col_data.astype(str).unique())

        # Handle unsupported or complex logic
        else:
            evaluated = "Not handled"

    except Exception as e:
        evaluated = "Error"

    evaluated_answers.append(evaluated)

# Add to the sheet
query_df["evaluated answer"] = evaluated_answers
query_df.to_excel("myquery.xlsx", index=False)
print("✅ Evaluated answers written to 'myquery.xlsx'")

✅ Evaluated answers written to 'myquery.xlsx'

In [32]:
df = pd.read_excel("myquery.xlsx")
df.head()

,question,row index,column index,answer,filtered row index,filtered column index,generated response,evaluated answer
0,What product line is in the latest entry?,999,3,Fashion accessories,NaN,NaN,acetate,Fashion accessories
1,On what date did the first transaction occur?,"17, 245, 450, 484, 496, 523, 567, 696, 829, 83...",7,1/1/2019,NaN,NaN,1889,1/1/2019
2,What is the latest transaction date?,"158, 306, 473, 474, 643, 646, 671, 881, 883, 9...",7,3/30/2019,NaN,NaN,"January 1, 2018",3/30/2019
3,what is the max rating given in home and lifes...,"2, 7, 19, 22, 25, 39, 40, 41, 54, 56, 58, 61, ...","3,10",9.9,NaN,NaN,a five star,Not handled
4,How many transactions involved Male customers ...,"331, 464, 540, 708, 710","2,10",5,NaN,NaN,0,Not handled

In [33]:
def match(generated, evaluated):
    return "Yes" if str(generated).strip().lower() == str(evaluated).strip().lower() else "No"

df["is_match"] = df.apply(lambda row: match(row["generated response"], row["evaluated answer"]), axis=1)
df.to_excel("myquery.xlsx", index=False)
print("✅ Match column added.")

✅ Match column added.

In [34]:
df = pd.read_excel("myquery.xlsx")
df.head()

,question,row index,column index,answer,filtered row index,filtered column index,generated response,evaluated answer,is_match
0,What product line is in the latest entry?,999,3,Fashion accessories,NaN,NaN,acetate,Fashion accessories,No
1,On what date did the first transaction occur?,"17, 245, 450, 484, 496, 523, 567, 696, 829, 83...",7,1/1/2019,NaN,NaN,1889,1/1/2019,No
2,What is the latest transaction date?,"158, 306, 473, 474, 643, 646, 671, 881, 883, 9...",7,3/30/2019,NaN,NaN,"January 1, 2018",3/30/2019,No
3,what is the max rating given in home and lifes...,"2, 7, 19, 22, 25, 39, 40, 41, 54, 56, 58, 61, ...","3,10",9.9,NaN,NaN,a five star,Not handled,No
4,How many transactions involved Male customers ...,"331, 464, 540, 708, 710","2,10",5,NaN,NaN,0,Not handled,No

In [35]:
correct = (query_df['answer'].astype(str) == query_df['evaluated answer'].astype(str)).sum()
accuracy = correct / len(query_df)
print(f"Accuracy: {accuracy:.2%}")

Accuracy: 25.71%